name: PR checks oquturbo

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run local tests
        run: ./gradlew test

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-key.jks

      - name: Build APK
        run: ./gradlew :app:oquturbo:androidApp:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        if: success()

      - name: Rename APK
        run: mv app/oquturbo/androidApp/build/outputs/apk/release/androidApp-release.apk app/oquturbo/androidApp/build/outputs/apk/release/oquturbo.apk
        if: success()

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/oquturbo/androidApp/build/outputs/apk/release/oquturbo.apk
        if: success()

  post-build-android:
    needs: build-android
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout io repository
        uses: actions/checkout@v4
        with:
          repository: 'alad1nks/alad1nks.github.io'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: oquturbo/oquturbo/${{ github.head_ref || github.ref_name }}

      - name: Commit APK
        run: |
          git config --local user.name 'alad1nks'
          git config --local user.email 'alad1nks@users.noreply.github.com'
          git add oquturbo/oquturbo/${{ github.head_ref || github.ref_name }}/*.apk
          git commit -m 'Add generated APK file for oquturbo'
          git push

  build-ios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build iOS
        run: ./gradlew :app:oquturbo:shared:linkReleaseFrameworkIosArm64

  build-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build js
        run: ./gradlew :app:oquturbo:webApp:jsJar

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build wasm
        run: ./gradlew :app:oquturbo:webApp:wasmJsJar

  build-jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build jvm
        run: ./gradlew :app:oquturbo:desktopApp:jar
