name: PR checks sansprint

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'app/sansprint/**'
      - 'feature/remembernumber/**'
      - 'feature/remembernumbermenu/**'
      - 'feature/main/**'
      - 'core/**'
      - 'resources/**'
      - '.github/workflows/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Android
        run: ./gradlew :app:sansprint:androidApp:assembleDebug

  build-ios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build iOS
        run: ./gradlew :app:sansprint:shared:linkReleaseFrameworkIosArm64

  build-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build js
        run: ./gradlew :app:sansprint:webApp:jsJar

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build wasm
        run: ./gradlew :app:sansprint:webApp:wasmJsJar

  build-jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build jvm
        run: ./gradlew :app:sansprint:desktopApp:jar
